# Generated by Django 3.0.1 on 2019-12-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('cedula', models.PositiveSmallIntegerField(blank=True, verbose_name='Cedula')),
                ('telefono', models.PositiveSmallIntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLocal', models.PositiveIntegerField(blank=True, verbose_name='idLocal')),
                ('idEmpleado', models.PositiveIntegerField(blank=True, verbose_name='idEmpleado')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLocal', models.CharField(max_length=50, verbose_name='Local')),
                ('direccion', models.CharField(max_length=60, verbose_name='Direccion')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('telefono', models.PositiveSmallIntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.ImageField(blank=True, upload_to='', verbose_name='Imagen')),
                ('precio', models.FloatField(blank=True, verbose_name='Precio')),
                ('detalle', models.CharField(max_length=80, verbose_name='Detalle')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistas', models.PositiveIntegerField(verbose_name='Vistas')),
                ('likes', models.PositiveIntegerField(verbose_name='Likes')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=30, verbose_name='Rol')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50, verbose_name='TipoLocal')),
                ('mayorista', models.BooleanField(default=False, verbose_name='TallerMayorista')),
                ('minorista', models.BooleanField(default=False, verbose_name='TallerMinorista')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, verbose_name='User')),
                ('paswword', models.CharField(blank=True, max_length=20, verbose_name='Password')),
            ],
        ),
    ]
