# Generated by Django 3.0.1 on 2019-12-29 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombres', models.CharField(blank=True, help_text='Ej: Juan Carlos', max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, help_text='Ej: Castro Fernandez', max_length=50, verbose_name='Apellidos')),
                ('cedula', models.PositiveIntegerField(blank=True, help_text='Ej: 0123456789', primary_key=True, serialize=False, verbose_name='Cedula')),
                ('telefono', models.PositiveSmallIntegerField(help_text='Ej: 0987654321', verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistas', models.PositiveIntegerField(verbose_name='Vistas')),
                ('likes', models.PositiveIntegerField(verbose_name='Likes')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=30, verbose_name='Rol')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50, verbose_name='TipoLocal')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, verbose_name='User')),
                ('paswword', models.CharField(blank=True, max_length=20, verbose_name='Password')),
                ('empleadoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.Empleado')),
                ('rolFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.ImageField(blank=True, upload_to='', verbose_name='Imagen')),
                ('precio', models.FloatField(blank=True, help_text='Ej: 10.50', verbose_name='Precio')),
                ('detalle', models.CharField(max_length=80, verbose_name='Detalle')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('reaccionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.Reaccion')),
                ('tipoProductoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.TipoProducto')),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('nombreLocal', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Local')),
                ('direccion', models.CharField(blank=True, max_length=60, verbose_name='Direccion')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('telefono', models.PositiveSmallIntegerField(verbose_name='Telefono')),
                ('tipoLocalFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_model.TipoLocal')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.Empleado')),
                ('idLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_model.Local')),
            ],
        ),
    ]
